language: node_js
node_js:
- node
cache: yarn
script: yarn verify
deploy:
  - provider: heroku
    api_key: $AUTHOR_HEROKU_KEY
  - provider: npm
    email: $AUTHOR_EMAIL 
    api_key: $AUTHOR_NPM_TOKEN
    on:
      repo: eggheadio/egghead-ui
      tags: true
      branch: master
